### ISSUE TITLE
Editable profile

### ISSUE THREAD

**Issue by ihabdulr** [rmredder/StopBy#47]
1. create an editProfile activity 

- the editProfile activity should contain editText fields where user can edit their profile (base off current fields on profile page)
- add a submit button (we will provide actual code for pushing changes to the database

**Comment by ihabdulr** [comment]
I will respond to this soon. I have a few meetings to get through then I will get back to you.

**Comment by dannyara** [comment]
Rychard, there is another related task in which we would like someone to help us write a function on Profile.java that would give the user the option to edit their profile.

For this task, you will most likely have to create an EditProfile activity (EditProfile.xml & EditProfile.java) that will allow a user to edit their information and pass those changes onto the database.

**Comment by ihabdulr** [comment]
#101 complete.
