### ISSUE TITLE
Bug in the page where all locations are shown, weird user in California

### ISSUE THREAD

**Issue by joshuaemer** [rmredder/StopBy#61]
OS: Android 8.1.0
Description: This is a trivial bug or maybe this was intentional but the map shows someone in California with the name , and interests ".toString();

How to reproduce:
Just hit search and look at California.

Here's a picture:
![screenshot_20180328-211955](https://user-images.githubusercontent.com/22580003/38064931-ac1ea69e-32ce-11e8-99f7-f496b9eb6047.png)

**Comment by rmredder** [comment]
Working as intended :) , the tag is supposed to display the username and the users post. That is just what the user chose as their username and post and where they posted from (on an emulator you can set the location to anywhere you like). A smaller search radius is planned for beta.
