### ISSUE TITLE
[bug] can not finish conversation

### ISSUE THREAD

**Issue by littletoe** [rmredder/StopBy#91]
Didn't find a way to finish a conversation if I didn't want to talk to that guy any more.

![screenshot_20180414-181901](https://user-images.githubusercontent.com/14008278/38773165-3e8f2164-4014-11e8-8f46-88482ec47e76.jpg)

And can not distinguish each other
![screenshot_20180414-182338](https://user-images.githubusercontent.com/14008278/38773166-3e9d7ea8-4014-11e8-93ed-e4009cad5422.jpg)

**Comment by ihabdulr** [comment]
At the moment we do not have an "end conversation" action in place, however, we encourage you to stop talking to a person the moment you no longer have interest in a conversation with them via the 'back' button. If you decide you'd like to resume the conversation you may then enter the chat room again. In addition please note that this is not a 'bug' but a 'feature request'.

**Comment by ihabdulr** [comment]
Good question. We will consider this when implementing notification system.
